# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='dates',
        ),
    ]
