# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.TextField(),
        ),
    ]
