# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('wish', '0003_auto_20170530_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='add',
        ),
        migrations.AddField(
            model_name='wish',
            name='add',
            field=models.ManyToManyField(related_name='wished_by', to='login.User'),
        ),
    ]
